module.exports = {
  fontFamily: "Helvetica Neue, Helvetica, Arial, sans-serif",
  fontSizeAdjust: "none",
  fontSize: "100%",
  fontStyle: "normal",
  letterSpacing: "normal",
  fontStretch: "normal",
  fontVariant: "normal",
  fontWeight: "normal",
  font: "normal normal 100% Helvetica Neue, Helvetica, Arial, sans-serif",
  textAlignLast: "start",
  textDecoration: "none",
  textEmphasis: "none",
  textHeight: "auto",
  textIndent: 0,
  textJustify: "auto",
  textOutline: "none",
  textShadow: "none",
  textTransform: "none",
  textWrap: "normal",
  alignmentAdjust: "auto",
  alignmentBaseline: "baseline",
  animation: "none 0 ease 0 1 normal",
  animationPlayState: "running",
  appearance: "normal",
  azimuth: "center",
  backfaceVisibility: "visible",
  background: "none 0 0 auto repeat scroll padding-box transparent",
  backgroundColor: "transparent",
  backgroundImage: "none",
  baselineShift: "baseline",
  binding: "none",
  bleed: "6pt",
  bookmarkTarget: "none",
  border: "0 none transparent",
  borderRadius: 0,
  bottom: "auto",
  boxAlign: "stretch",
  boxDecorationBreak: "slice",
  boxDirection: "normal",
  boxFlex: 0.0,
  boxFlexGroup: 1,
  boxLines: "single",
  boxOrdinalGroup: 1,
  boxOrient: "inline-axis",
  boxPack: "start",
  boxShadow: "none",
  boxSizing: "content-box",
  breakAfter: "auto",
  breakBefore: "auto",
  breakInside: "auto",
  captionSide: top,
  clear: "none",
  clip: "auto",
  color: "inherit",
  colorProfile: "auto",
  columnCount: "auto",
  columnFill: "balance",
  columnGap: "normal",
  columnRule: "medium medium #1f1f1f",
  columnSpan: 1,
  columnWidth: "auto",
  columns: "auto auto",
  content: "normal",
  counterIncrement: "none",
  counterReset: "none",
  crop: "auto",
  cursor: "auto",
  direction: "ltr",
  display: "inline",
  dominantBaseline: "auto",
  dropInitialAfterAdjust: "text-after-edge",
  dropInitialAfterAlign: "baseline",
  dropInitialBeforeAdjust: "text-before-edge",
  dropInitialBeforeAlign: "caps-height",
  dropInitialSize: "auto",
  dropInitialValue: "initial",
  elevation: "level",
  emptyCells: "show",
  fit: "fill",
  fitPosition: "0% 0%",
  float: "none",
  floatOffset: "0 0",
  gridColumns: "none",
  gridRows: "none",
  hangingPunctuation: "none",
  height: "auto",
  hyphenateAfter: "auto",
  hyphenateBefore: "auto",
  hyphenateCharacter: "auto",
  hyphenateLines: "no-limit",
  hyphenateResource: "none",
  hyphens: "manual",
  icon: "auto",
  imageOrientation: "auto",
  imageRendering: "auto",
  imageResolution: "normal",
  inlineBoxAlign: "last",
  left: "auto",
  lineHeight: "inherit",
  lineStacking: "inline-line-height exclude-ruby consider-shifts",
  listStyle: "disc outside none",
  margin: 0,
  marks: "none",
  marqueeDirection: "forward",
  marqueeLoop: 1,
  marqueePlayCount: 1,
  marqueeSpeed: "normal",
  marqueeStyle: "scroll",
  maxHeight: "none",
  maxWidth: "none",
  minHeight: 0,
  minWidth: 0,
  moveTo: "normal",
  navDown: "auto",
  navIndex: "auto",
  navLeft: "auto",
  navRight: "auto",
  navUp: "auto",
  opacity: 1,
  orphans: 2,
  outline: "invert none medium",
  outlineOffset: 0,
  overflow: "visible",
  overflowStyle: "auto",
  padding: 0,
  page: "auto",
  pageBreakAfter: "auto",
  pageBreakBefore: "auto",
  pageBreakInside: "auto",
  pagePolicy: "start",
  perspective: "none",
  perspectiveOrigin: "50% 50%",
  position: "static",
  presentationLevel: 0,
  punctuationTrim: "none",
  quotes: "none",
  renderingIntent: "auto",
  resize: "none",
  right: "auto",
  rotation: 0,
  rotationPoint: "50% 50%",
  rubyAlign: "auto",
  rubyOverhang: "none",
  rubyPosition: "before",
  rubySpan: "none",
  size: "auto",
  stringSet: "none",
  tableLayout: "auto",
  top: "auto",
  transform: "none",
  transformOrigin: "50% 50% 0",
  transformStyle: "flat",
  transition: "all 0 ease 0",
  unicodeBidi: "normal",
  verticalAlign: "baseline",
  whiteSpace: "normal",
  whiteSpaceCollapse: "collapse",
  widows: 2,
  width: "auto",
  wordBreak: "normal",
  wordSpacing: "normal",
  wordWrap: "normal",
  zIndex: "auto",
  textAlign: "start"
};
